steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/fastapi-app", "."]

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    [
      'run',
      'deploy',
      'fastapi-app',
      '--image',
      'gcr.io/$PROJECT_ID/fastapi-app',
      '--platform',
      'managed',
      '--region',
      'us-central1',
      '--allow-unauthenticated',
      '--set-env-vars',
      'PROJECT_ID=$PROJECT_ID,LOCATION=us-central1',
    ]

images:
  - "gcr.io/$PROJECT_ID/fastapi-app"
